# Generated by Django 4.1 on 2022-11-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-11-11'),
            preserve_default=False,
        ),
    ]
